In [24]:
import pandas as pd 
import numpy as np 


In [3]:
#CONVERTENDO UM ARRAY PARA UMA SÉRIE
arr1=np.array([10,20,30])
serie1=pd.Series(arr1)
print(arr1)
print(serie1)


[10 20 30]
0    10
1    20
2    30
dtype: int64


In [4]:
#convertendo uma série pra um array:
arr2=serie1.to_numpy()
print(arr2)

[10 20 30]


In [5]:
#criação:
arr3=np.array([[1,2],[3,4]])
df_arr=pd.DataFrame(arr3,columns=['A','B'])
print(arr3)
print(df_arr)

[[1 2]
 [3 4]]
   A  B
0  1  2
1  3  4


In [6]:
#transformando uma coluna em uma série:
coluna_serie=df_arr['A']
print(coluna_serie)

0    1
1    3
Name: A, dtype: int64


In [7]:
#contagem de valores:
estados=pd.DataFrame({'Cidade':['RJ','SP','MG','ES','RJ','RJ','SP']})
print(estados['Cidade'].value_counts())
                     

Cidade
RJ    3
SP    2
MG    1
ES    1
Name: count, dtype: int64


In [8]:
#Cálculos Estatísticos:
notas=pd.DataFrame({'Notas':[10,8.5,7,7,7,7,5.6,6,8,8,7,9,10,4,9,8.5]})
print(notas['Notas'].sum()) #soma
print(notas['Notas'].mean()) #média
print(notas['Notas'].median()) #mediana
print(notas.describe()) # resumo de estatísticas

121.6
7.6
7.5
           Notas
count  16.000000
mean    7.600000
std     1.606238
min     4.000000
25%     7.000000
50%     7.500000
75%     8.625000
max    10.000000


Atividade 1

Crie um Array unidimnesional com os números de 1 a 12. Transforme este array em uma matriz de 3 linhas e quatro colunas.
(Desafio: Aplique a transposição da matriz para criar as dimensões em 4x3 (.trampose) e, em seguida, crie um array unidimensional (.flatten))

Atividade 2

Leia o arquivo ClassicoDisco.csv trabalhando em aulas anteriore e aplique o comando describe() para gerar uma análise estatística das últimas linnhas do Dataset com apoio nesta atividade

In [30]:
#Atividade 1
array = np.arange(1,13)
print(array)
matriz_3x4 = array.reshape(3, 4) 
print("Matriz 3x4:\n", matriz_3x4)

#desafio
matriz_4x3 = matriz_3x4.transpose() 
print("Matriz 4x3 (transposta):\n", matriz_4x3) 

array_flatten = matriz_4x3.flatten() 
print("Array unidimensional:\n", array_flatten)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Matriz 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matriz 4x3 (transposta):
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
Array unidimensional:
 [ 1  5  9  2  6 10  3  7 11  4  8 12]


In [29]:
#Atividade 2

df_disco = pd.read_csv('C:\\Users\\unidade.copacabana\\Documents\\BigDataSenac\\UC2\\ClassicDisco.csv')
ultimas_linhas = df_disco.tail() 
analise_estatistica = ultimas_linhas.describe() 
print(analise_estatistica)

         Year       Duration  Time_Signature  Danceability    Energy  \
count     5.0       5.000000             5.0      5.000000  5.000000   
mean   1979.0  322579.000000             4.0      0.659200  0.907400   
std       0.0   80231.120066             0.0      0.032097  0.062304   
min    1979.0  208200.000000             4.0      0.633000  0.840000   
25%    1979.0  299510.000000             4.0      0.633000  0.854000   
50%    1979.0  306818.000000             4.0      0.649000  0.901000   
75%    1979.0  390567.000000             4.0      0.672000  0.970000   
max    1979.0  407800.000000             4.0      0.709000  0.972000   

             Key  Loudness  Mode  Speechiness  Acousticness  Instrumentalness  \
count   5.000000   5.00000   5.0      5.00000      5.000000          5.000000   
mean    6.000000  -6.35860   1.0      0.05708      0.011308          0.223529   
std     3.082207   2.57186   0.0      0.04591      0.022023          0.392843   
min     2.000000 -10.24800 

#count: O número de valores não-nulos na coluna.
#mean: A média aritmética dos valores.
#std: O desvio padrão, que mede a quantidade de variação ou dispersão dos valores.
#min: O valor mínimo na coluna.
#25% (primeiro quartil): O valor abaixo do qual 25% dos dados se encontram.
#50% (mediana): O valor central, abaixo do qual 50% dos dados se encontram.
#75% (terceiro quartil): O valor abaixo do qual 75% dos dados se encontram.
#max: O valor máximo na coluna.